[package]
name = "lenia"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
pixel-canvas = "0.2.3"
rustfft = "6.1.0"
rayon = "1.8.0"

[dependencies.ndarray]
version = "0.15.6"
features = ["rayon"]